package curso06_Java_Excecoes.c1_Try_Catch;

public class ContaTest {
    void deposita() throws MinhaExcecao{}
}
